TSPP/Controllers/CinemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TSPP.Models.DB;

namespace TSPP.Controllers
{
    public class CinemaController : Controller
    {
        private readonly Cinema1Context _context;

        public CinemaController(Cinema1Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var cookie = Request.Cookies["User"];
            if (cookie != null)
            {
                ViewBag.UserId = cookie;
            }
            return View(_context.Cinema);

        }

        public IActionResult Info(int? id)
        {
            var cookie = Request.Cookies["User"];
            if (cookie != null)
            {
                ViewBag.UserId = cookie;
            }
            if (id != null)
            {
                // var res = _context.Cinema.Select(x => x).Where(x => x.CinemaId == id);
                List<Cinema> c = _context.Cinema.Where(x => x.CinemaId == id).ToList();
                Cinema s = c[0];
                return View(s);
            }
            else
            {
                return RedirectToPage("Error");
            }



        }
    }
}

TSPP/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TSPP.Models.DB;
using TSPP.Models.ViewModels;

namespace TSPP.Controllers
{
    public class SessionController : Controller
    {
        private readonly Cinema1Context _context;

        public SessionController(Cinema1Context context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var res = _context.Session.Select(x => x).ToList();
            var res1 = from _session in _context.Session
                       join _movie in _context.Movie on _session.MovieId equals _movie.MovieId
                       select new
                       {
                           SessionId = _session.SessionId,
                           Date = _session.DateTime,
                           MovieId = _movie.MovieId,
                           MovieName = _movie.Name,
                           MovieImg = _movie.Img,
                           HallId = _session.HallId
                       };
            var res2 = from _session in res1
                       join _cinemasession in _context.CinemaSession on _session.SessionId equals _cinemasession.SessionId
                       select new
                       {
                           CinemaId = _cinemasession.CinemaId,
                           SessionId = _session.SessionId
                       };

            var res3 = from _cinemasession in res2
                       join _cinema in _context.Cinema on _cinemasession.CinemaId equals _cinema.CinemaId
                       select new
                       {
                           SessionId = _cinemasession.SessionId,
                           CinemaId = _cinema.CinemaId,
                           CinemaName = _cinema.Name
                       };
            var res4 = from r1 in res1
                       join r3 in res3 on r1.SessionId equals r3.SessionId
                       select new
                       {
                           SessionId = r1.SessionId,
                           Date = r1.Date,
                           HallId = r1.HallId,
                           MovieId = r1.MovieId,
                           MovieName = r1.MovieName,
                           MovieImg = r1.MovieImg,
                           CinemaId = r3.CinemaId,
                           CinemaName = r3.CinemaName
                       };

            List<SessionsModel> list=new List<SessionsModel>();
            foreach (var item in res4)
            {
                SessionsModel s=new SessionsModel(item.SessionId,item.Date,item.HallId,item.MovieId,item.MovieName,item.MovieImg,item.CinemaId,item.CinemaName);
                list.Add(s);
            }
            var cookie = Request.Cookies["User"];
            if (cookie != null)
            {
                ViewBag.UserId = cookie;
            }

            return View(list);
        }
        public IActionResult Session()
        {
            return View();
        }
    }
}

TSPP/Views/Shared/PartialCommentView.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<int>

    @{ 
        int[] k=new int[2];
        k[0] = Model.First<int>();
        k[1] = Model.Last<int>();
    }

@using (Html.BeginForm(actionName: "Comment", controllerName:"Movies"))
{
    <fieldset>
        <legend>

            <textarea name="comment" rows="5" cols="50"></textarea>
            <input type="hidden" name="UserId" value="@k[0]">
            <input type="hidden" name="MovieId" value="@k[1]">
            <button type="submit" class="btn btn-info">Залишити коментар</button>
        </legend>
    </fieldset>
}

TSPP/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TSPP</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body style="background-color: lightgray">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Movies" asp-action="Show" class="navbar-brand">TSPP</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Cinema" asp-action="Index">Cinema</a></li>
                    <li><a asp-area="" asp-controller="Movies" asp-action="Index">Movies</a></li>
                    <li><a asp-area="" asp-controller="Session" asp-action="Index">Sessions</a></li>
                </ul>
                <form class="navbar-form navbar-left" method="post" action="/Search/Search">
                    <div class="form-group">
                        <input type="text" class="form-control" name="search" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-danger">Пошук</button>
                </form>
                @if (IsSectionDefined("user_exit"))
                {
                    @RenderSection("user_exit");
                }
                else
                {
                    @RenderSection("login_register", required: false)
                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" asp-controller="Users" asp-action="LogIn">Вхід</a></li>
                        <li><a asp-area="" asp-controller="Users" asp-action="Register">Реєстрація</a></li>
                    </ul>
                }

            </div>

        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - TSPP</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>