TSPP/Areas/Admin/Controllers/AddInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TSPP.Models.DB;
using TSPP.Areas.Admin.Models;
using System.IO;

namespace TSPP.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AddInfoController : Controller
    {
        private readonly Cinema1Context _context;

        public AddInfoController(Cinema1Context context)
        {
            _context = context;
        }
        public ActionResult AddMovie()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddMovie(MovieAddModel mam)
        {
            Movie m = new Movie() { Name = mam.moviename, Discription = mam.discription, Length = Convert.ToInt32(mam.length), Tecnology = mam.technology };
            if (mam.image != null)
            {
                byte[] imageData = null;

                using (var binaryReader = new BinaryReader(mam.image.OpenReadStream()))
                {
                    imageData = binaryReader.ReadBytes((int)mam.image.Length);
                }
                // установка массива байтов
                m.Img = imageData;
            }
            _context.Movie.Add(m);
            _context.SaveChanges();
            return RedirectToAction("AddMovie");
        }

        public ActionResult AddCinema()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddCinema(string cinemaname, string address)
        {
            Cinema c = new Cinema() { Name = cinemaname, Address = address, SessionId = 7 };
            _context.Cinema.Add(c);
            _context.SaveChanges();
            return RedirectToAction("AddMovie");
        }



        public ActionResult AddSession()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddSession(string movieid, string hallid, string datetime)
        {
            Session s = new Session() { MovieId = Convert.ToInt32(movieid), HallId = Convert.ToInt32(hallid), DateTime = Convert.ToDateTime(datetime) };
            _context.Session.Add(s);
            _context.SaveChanges();
            return RedirectToAction("AddMovie");
        }
        public ActionResult AddUser()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddUser(string name, string email, string password, bool isadmin)
        {
            var res = _context.Users.Where(x => x.Email == email).Select(x => x.UserId).ToList();
            if (res.Count != 0)
            {
                return RedirectToAction("AddMovie");
            }
            else
            {
                Users u = new Users() { Name = name, Email = email, Password = password, IsAdmin = isadmin };
            _context.Users.Add(u);
                _context.SaveChanges();
                return RedirectToAction("AddMovie");
            }

        }


    }
}

TSPP/Areas/Admin/Views/AddInfo/AddCinema.cshtml
@{
    ViewData["Title"] = "AddCinema";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row">

    <div class="col-md-6">
        <form asp-action="AddCinema" asp-controller="AddInfo" method="post">

            <fieldset>
                <legend>Add new cinema:</legend>
                Назва кінотеатру:<br>
                <input class="form-control" type="text" name="cinemaname" /><br>
                Адреса:<br>
                <input class="form-control" type="text" name="address"><br>

                <input type="submit" class="btn btn-primary" value="Додати фільм">
            </fieldset>
        </form>
    </div>
    <div class="col-md-6">
       

        @Html.ActionLink("Додати фільм", "AddMovie", "AddInfo");


    </div>



</div>

TSPP/Areas/Admin/Views/AddInfo/AddMovie.cshtml
@model TSPP.Areas.Admin.Models.MovieAddModel

@{
    ViewData["Title"] = "AddMovie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">

    <div class="col-md-6">
        <form asp-action="AddMovie" asp-controller="AddInfo" method="post" enctype="multipart/form-data">

            <fieldset>
                <legend>Add new movie:</legend>
                Назва фільму:<br>
                <input class="form-control" type="text" name="moviename" /><br>
                Опис:<br>
                <input class="form-control" type="text" name="discription"><br>
                Тривалість:<br>
                <input class="form-control" type="text" name="length"><br>
                Обкладинка
                <input class="form-control" type="file" name="image" multiple />
                Технологія показу:<br>
                <input class="form-control" type="text" name="technology"><br>
                <input type="submit" class="btn btn-primary" value="Додати фільм">
            </fieldset>
        </form>
    </div>
    <div class="col-md-6">

        <hr />


        @Html.ActionLink("Додати сеанс", "AddSession", "AddInfo")
       
        <hr />


        @Html.ActionLink("Додати кінотеатр", "AddCinema", "AddInfo")
        
        <hr />

        @Html.ActionLink("Додати користувача", "AddUser", "AddInfo")
    </div>



</div>





@section user_exit
    {
    <ul class="nav navbar-nav navbar-right">
        <li><a asp-area="" asp-controller="Users" asp-action="Exit">Вихід</a></li>
    </ul>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TSPP/Areas/Admin/Views/AddInfo/AddSession.cshtml
@using TSPP.Models.DB
@{
    ViewData["Title"] = "AddSession";
    Layout = "~/Views/Shared/_Layout.cshtml";

    <div class="row">

        <div class="col-md-6">
            <form asp-action="AddSession" asp-controller="AddInfo" method="post" enctype="multipart/form-data">

                <fieldset>
                    <legend>Додати сеанс</legend>
                    ID фільму:<br>
                    <input class="form-control" type="text" name="movieid" /><br>
                    ID залу:<br>
                    <input class="form-control" type="text" name="hallid"><br>
                    Час і дата:<br>
                    <input class="form-control" type="datetime" name="datetime"><br>
                    <input type="submit" class="btn btn-primary" value="Додати фільм">
                </fieldset>
            </form>
        </div>
        <div class="col-md-6">

            <hr />


            @Html.ActionLink("Додати сеанс", "AddSession", "AddInfo")

            <hr />


            @Html.ActionLink("Додати кінотеатр", "AddCinema", "AddInfo")

            <hr />

            @Html.ActionLink("Додати користувача", "AddUser", "AddInfo")
        </div>



    </div>





    @section user_exit
        {
        <ul class="nav navbar-nav navbar-right">
            <li><a asp-area="" asp-controller="Users" asp-action="Exit">Вихід</a></li>
        </ul>
    }

}

TSPP/Areas/Admin/Views/AddInfo/AddUser.cshtml
@model TSPP.Models.DB.Users

@{
    ViewData["Title"] = "AddUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddUser</h2>

<div class="row">

    <div class="col-md-6">
        <form asp-action="AddUser" asp-controller="AddInfo" method="post">

            <fieldset>
                <legend>Додати користувача:</legend>
                Ім'я:<br>
                <input class="form-control" type="text" name="name" /><br>
                Емейл:<br>
                <input class="form-control" type="text" name="email"><br>
                Пароль:<br>
                <input class="form-control" type="text" name="password"><br>
                IsAdmin               
                <input class="form-control" type="checkbox" name="isadmin" />
                <input type="submit" class="btn btn-primary" value="Додати користувача">
            </fieldset>
        </form>
    </div>
    <div class="col-md-6">

        <hr />


        @Html.ActionLink("Додати сеанс", "AddSession", "AddInfo")

        <hr />


        @Html.ActionLink("Додати кінотеатр", "AddCinema", "AddInfo")

        <hr />

        @Html.ActionLink("Додати користувача", "AddUser", "AddInfo")
    </div>



</div>





@section user_exit
    {
    <ul class="nav navbar-nav navbar-right">
        <li><a asp-area="" asp-controller="Users" asp-action="Exit">Вихід</a></li>
    </ul>
}